id: A561D3FDB
title: 'Melody to Delight Padma: A Long-Life Prayer and Name Offering for the Rebirth
  of Chokgyur Lingpa'
type: translation
pechas:
- I99497941
- I4CDF100F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:15:16.617718
  last_modified_at: 2023-01-04 12:15:16.617724
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I99497941/9B44: 56E0
  I4CDF100F/94F8: 56E0
